################################################################################
# Client configuration parameters for submission of twister2 jobs
################################################################################

# twister2 job name
twister2.job.name: "basic-kubernetes"

# number of CPUs for this job
twister2.cpu_per_container: "1"

# amount of memory for each CPU in bytes, 1GB=1024*1024*1024
twister2.ram_per_container: "1024"

# amount of hard disk space on each CPU in bytes, 1GB=1024*1024*1024
twister2.disk_per_container: "1024"

# number of instances for the task
twister2.number_of_containers: "12"

# number of containers per pod
# default is 1
# number_of_containers must be divisible by containers_per_pod
kubernetes.containers_per_pod: "3"
