# This is the Persistent Volume object that is sent to Kubernetes master 
# when creating a persistent volume for a Twister2 job

apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-<job-name>
spec:
  accessModes:
  - <kubernetes.storage.access.mode>
  capacity:
    storage: <persistent.volume.total>
  nfs:
    path: <nfs.server.path>
    server: <nfs.server.address>
  persistentVolumeReclaimPolicy: <kubernetes.storage.reclaim.policy>
  storageClassName: <kubernetes.persistent.storage.class>

